org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=26.1.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT
# Mod Properties
mod_version=2.2.0
maven_group=org.multicoder
archives_base_name=mcpaintball
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.152.1+26.1.2
voicechat_api_version=2.6.20
voicechat_version=2.6.20+26.1.2