package org.multicoder.mcpaintball.entity;

import net.fabricmc.fabric.api.object.builder.v1.entity.FabricEntityTypeBuilder;
import net.minecraft.entity.EntityDimensions;
import net.minecraft.entity.EntityType;
import net.minecraft.entity.SpawnGroup;
import net.minecraft.entity.projectile.PersistentProjectileEntity;
import net.minecraft.entity.projectile.thrown.ThrownItemEntity;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.util.Identifier;
import org.multicoder.mcpaintball.MCPaintball;
import org.multicoder.mcpaintball.entity.grenade.*;
import org.multicoder.mcpaintball.entity.paintball.*;
import org.multicoder.mcpaintball.entity.rockets.*;

public class MCPaintballEntities {
    public static final EntityType<? extends PersistentProjectileEntity> RED_PAINTBALL = Registry.register(Registries.ENTITY_TYPE, new Identifier(MCPaintball.MOD_ID, "red_paintball"), FabricEntityTypeBuilder.<PersistentProjectileEntity>create(SpawnGroup.MISC, RedPaintballEntity::new).dimensions(EntityDimensions.fixed(0.5f, 0.5f)).build());
    public static final EntityType<? extends PersistentProjectileEntity> BLUE_PAINTBALL = Registry.register(Registries.ENTITY_TYPE, new Identifier(MCPaintball.MOD_ID, "blue_paintball"), FabricEntityTypeBuilder.<PersistentProjectileEntity>create(SpawnGroup.MISC, BluePaintballEntity::new).dimensions(EntityDimensions.fixed(0.5f, 0.5f)).build());
    public static final EntityType<? extends PersistentProjectileEntity> GREEN_PAINTBALL = Registry.register(Registries.ENTITY_TYPE, new Identifier(MCPaintball.MOD_ID, "green_paintball"), FabricEntityTypeBuilder.<PersistentProjectileEntity>create(SpawnGroup.MISC, GreenPaintballEntity::new).dimensions(EntityDimensions.fixed(0.5f, 0.5f)).build());
    public static final EntityType<? extends PersistentProjectileEntity> CYAN_PAINTBALL = Registry.register(Registries.ENTITY_TYPE, new Identifier(MCPaintball.MOD_ID, "cyan_paintball"), FabricEntityTypeBuilder.<PersistentProjectileEntity>create(SpawnGroup.MISC, CyanPaintballEntity::new).dimensions(EntityDimensions.fixed(0.5f, 0.5f)).build());
    public static final EntityType<? extends PersistentProjectileEntity> MAGENTA_PAINTBALL = Registry.register(Registries.ENTITY_TYPE, new Identifier(MCPaintball.MOD_ID, "magenta_paintball"), FabricEntityTypeBuilder.<PersistentProjectileEntity>create(SpawnGroup.MISC, MagentaPaintballEntity::new).dimensions(EntityDimensions.fixed(0.5f, 0.5f)).build());
    public static final EntityType<? extends PersistentProjectileEntity> LIME_PAINTBALL = Registry.register(Registries.ENTITY_TYPE, new Identifier(MCPaintball.MOD_ID, "lime_paintball"), FabricEntityTypeBuilder.<PersistentProjectileEntity>create(SpawnGroup.MISC, LimePaintballEntity::new).dimensions(EntityDimensions.fixed(0.5f, 0.5f)).build());
    public static final EntityType<? extends PersistentProjectileEntity> LIGHT_BLUE_PAINTBALL = Registry.register(Registries.ENTITY_TYPE, new Identifier(MCPaintball.MOD_ID, "light_blue_paintball"), FabricEntityTypeBuilder.<PersistentProjectileEntity>create(SpawnGroup.MISC, LightBluePaintballEntity::new).dimensions(EntityDimensions.fixed(0.5f, 0.5f)).build());
    public static final EntityType<? extends PersistentProjectileEntity> PINK_PAINTBALL = Registry.register(Registries.ENTITY_TYPE, new Identifier(MCPaintball.MOD_ID, "pink_paintball"), FabricEntityTypeBuilder.<PersistentProjectileEntity>create(SpawnGroup.MISC, PinkPaintballEntity::new).dimensions(EntityDimensions.fixed(0.5f, 0.5f)).build());
    public static final EntityType<? extends PersistentProjectileEntity> PURPLE_PAINTBALL = Registry.register(Registries.ENTITY_TYPE, new Identifier(MCPaintball.MOD_ID, "purple_paintball"), FabricEntityTypeBuilder.<PersistentProjectileEntity>create(SpawnGroup.MISC, PurplePaintballEntity::new).dimensions(EntityDimensions.fixed(0.5f, 0.5f)).build());

    public static final EntityType<? extends PersistentProjectileEntity> RED_PAINTBALL_ROCKET = Registry.register(Registries.ENTITY_TYPE, new Identifier(MCPaintball.MOD_ID, "red_paintball_rocket"), FabricEntityTypeBuilder.<PersistentProjectileEntity>create(SpawnGroup.MISC, RedPaintballRocketEntity::new).dimensions(EntityDimensions.fixed(0.5f, 0.5f)).build());
    public static final EntityType<? extends PersistentProjectileEntity> BLUE_PAINTBALL_ROCKET = Registry.register(Registries.ENTITY_TYPE, new Identifier(MCPaintball.MOD_ID, "green_paintball_rocket"), FabricEntityTypeBuilder.<PersistentProjectileEntity>create(SpawnGroup.MISC, GreenPaintballRocketEntity::new).dimensions(EntityDimensions.fixed(0.5f, 0.5f)).build());
    public static final EntityType<? extends PersistentProjectileEntity> GREEN_PAINTBALL_ROCKET = Registry.register(Registries.ENTITY_TYPE, new Identifier(MCPaintball.MOD_ID, "blue_paintball_rocket"), FabricEntityTypeBuilder.<PersistentProjectileEntity>create(SpawnGroup.MISC, BluePaintballRocketEntity::new).dimensions(EntityDimensions.fixed(0.5f, 0.5f)).build());
    public static final EntityType<? extends PersistentProjectileEntity> CYAN_PAINTBALL_ROCKET = Registry.register(Registries.ENTITY_TYPE, new Identifier(MCPaintball.MOD_ID, "cyan_paintball_rocket"), FabricEntityTypeBuilder.<PersistentProjectileEntity>create(SpawnGroup.MISC, CyanPaintballRocketEntity::new).dimensions(EntityDimensions.fixed(0.5f, 0.5f)).build());
    public static final EntityType<? extends PersistentProjectileEntity> MAGENTA_PAINTBALL_ROCKET = Registry.register(Registries.ENTITY_TYPE, new Identifier(MCPaintball.MOD_ID, "magenta_paintball_rocket"), FabricEntityTypeBuilder.<PersistentProjectileEntity>create(SpawnGroup.MISC, MagentaPaintballRocketEntity::new).dimensions(EntityDimensions.fixed(0.5f, 0.5f)).build());
    public static final EntityType<? extends PersistentProjectileEntity> LIME_PAINTBALL_ROCKET = Registry.register(Registries.ENTITY_TYPE, new Identifier(MCPaintball.MOD_ID, "lime_paintball_rocket"), FabricEntityTypeBuilder.<PersistentProjectileEntity>create(SpawnGroup.MISC, LimePaintballRocketEntity::new).dimensions(EntityDimensions.fixed(0.5f, 0.5f)).build());
    public static final EntityType<? extends PersistentProjectileEntity> LIGHT_BLUE_PAINTBALL_ROCKET = Registry.register(Registries.ENTITY_TYPE, new Identifier(MCPaintball.MOD_ID, "light_blue_paintball_rocket"), FabricEntityTypeBuilder.<PersistentProjectileEntity>create(SpawnGroup.MISC, LightBluePaintballRocketEntity::new).dimensions(EntityDimensions.fixed(0.5f, 0.5f)).build());
    public static final EntityType<? extends PersistentProjectileEntity> PINK_PAINTBALL_ROCKET = Registry.register(Registries.ENTITY_TYPE, new Identifier(MCPaintball.MOD_ID, "pink_paintball_rocket"), FabricEntityTypeBuilder.<PersistentProjectileEntity>create(SpawnGroup.MISC, PinkPaintballRocketEntity::new).dimensions(EntityDimensions.fixed(0.5f, 0.5f)).build());
    public static final EntityType<? extends PersistentProjectileEntity> PURPLE_PAINTBALL_ROCKET = Registry.register(Registries.ENTITY_TYPE, new Identifier(MCPaintball.MOD_ID, "purple_paintball_rocket"), FabricEntityTypeBuilder.<PersistentProjectileEntity>create(SpawnGroup.MISC, PurplePaintballRocketEntity::new).dimensions(EntityDimensions.fixed(0.5f, 0.5f)).build());

    public static final EntityType<? extends ThrownItemEntity> RED_GRENADE = Registry.register(Registries.ENTITY_TYPE, new Identifier(MCPaintball.MOD_ID, "red_grenade"), FabricEntityTypeBuilder.<ThrownItemEntity>create(SpawnGroup.MISC, RedGrenadeEntity::new).dimensions(EntityDimensions.fixed(1f, 1f)).trackRangeBlocks(16).trackedUpdateRate(10).build());
    public static final EntityType<? extends ThrownItemEntity> GREEN_GRENADE = Registry.register(Registries.ENTITY_TYPE, new Identifier(MCPaintball.MOD_ID, "green_grenade"), FabricEntityTypeBuilder.<ThrownItemEntity>create(SpawnGroup.MISC, GreenGrenadeEntity::new).dimensions(EntityDimensions.fixed(1f, 1f)).trackRangeBlocks(16).trackedUpdateRate(10).build());
    public static final EntityType<? extends ThrownItemEntity> BLUE_GRENADE = Registry.register(Registries.ENTITY_TYPE, new Identifier(MCPaintball.MOD_ID, "blue_grenade"), FabricEntityTypeBuilder.<ThrownItemEntity>create(SpawnGroup.MISC, BlueGrenadeEntity::new).dimensions(EntityDimensions.fixed(1f, 1f)).trackRangeBlocks(16).trackedUpdateRate(10).build());
    public static final EntityType<? extends ThrownItemEntity> CYAN_GRENADE = Registry.register(Registries.ENTITY_TYPE, new Identifier(MCPaintball.MOD_ID, "cyan_grenade"), FabricEntityTypeBuilder.<ThrownItemEntity>create(SpawnGroup.MISC, CyanGrenadeEntity::new).dimensions(EntityDimensions.fixed(1f, 1f)).trackRangeBlocks(16).trackedUpdateRate(10).build());
    public static final EntityType<? extends ThrownItemEntity> MAGENTA_GRENADE = Registry.register(Registries.ENTITY_TYPE, new Identifier(MCPaintball.MOD_ID, "magenta_grenade"), FabricEntityTypeBuilder.<ThrownItemEntity>create(SpawnGroup.MISC, MagentaGrenadeEntity::new).dimensions(EntityDimensions.fixed(1f, 1f)).trackRangeBlocks(16).trackedUpdateRate(10).build());
    public static final EntityType<? extends ThrownItemEntity> LIME_GRENADE = Registry.register(Registries.ENTITY_TYPE, new Identifier(MCPaintball.MOD_ID, "lime_grenade"), FabricEntityTypeBuilder.<ThrownItemEntity>create(SpawnGroup.MISC, LimeGrenadeEntity::new).dimensions(EntityDimensions.fixed(1f, 1f)).trackRangeBlocks(16).trackedUpdateRate(10).build());
    public static final EntityType<? extends ThrownItemEntity> LIGHT_BLUE_GRENADE = Registry.register(Registries.ENTITY_TYPE, new Identifier(MCPaintball.MOD_ID, "light_blue_grenade"), FabricEntityTypeBuilder.<ThrownItemEntity>create(SpawnGroup.MISC, LightBlueGrenadeEntity::new).dimensions(EntityDimensions.fixed(1f, 1f)).trackRangeBlocks(16).trackedUpdateRate(10).build());
    public static final EntityType<? extends ThrownItemEntity> PINK_GRENADE = Registry.register(Registries.ENTITY_TYPE, new Identifier(MCPaintball.MOD_ID, "pink_grenade"), FabricEntityTypeBuilder.<ThrownItemEntity>create(SpawnGroup.MISC, PinkGrenadeEntity::new).dimensions(EntityDimensions.fixed(1f, 1f)).trackRangeBlocks(16).trackedUpdateRate(10).build());
    public static final EntityType<? extends ThrownItemEntity> PURPLE_GRENADE = Registry.register(Registries.ENTITY_TYPE, new Identifier(MCPaintball.MOD_ID, "purple_grenade"), FabricEntityTypeBuilder.<ThrownItemEntity>create(SpawnGroup.MISC, PurpleGrenadeEntity::new).dimensions(EntityDimensions.fixed(1f, 1f)).trackRangeBlocks(16).trackedUpdateRate(10).build());

    public static void registerModEntities() {
        MCPaintball.LOGGER.info("Adding Entities");
    }
}
