modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
issueTrackerURL="https://github.com/Multi-Coder-24/MCPaintball/issues"
[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
updateJSONURL="https://api.modrinth.com/updates/mc-paintball/forge_updates.json?neoforge=only"
displayURL="https://modrinth.com/project/mc-paintball"
logoFile="assets/mcpaintball/icon.png"
authors = "${mod_authors}"
description = '''${mod_description}'''
[[dependencies."${mod_id}"]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"
[[dependencies."${mod_id}"]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
[[dependencies."${mod_id}"]]
modId="voicechat_api"
type="optional"
versionRange="[${voicechat_api_version},)"
ordering="AFTER"
side="BOTH"